### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by shabier** [cmda-bt/js-bootcamp-19-20#35]
# My Introduction

## Name
Shabier

## Class
TECH-4

## About me
Beginner developer that likes building fun projects

## Skill level
Beginner

## GitHub username
sjagoori

## GitHub repository
https://github.com/sjagoori/js-bootcamp

**Comment by dandevri** [comment]
👋 Shabier

Looks pretty good! You might want to expand your notes a bit while you continue working on front-end, you'll need those later!
