### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by mikehov** [cmda-bt/js-bootcamp-19-20#38]
# My Introduction

## Name
Mike Hovenier

## Class
TECH-4 

## About me
Mike Hovenier, 21 years old, I live near Haarlem. Loves to play game here and there, writing songs cause, trying to learn the guitar and piano lately, because of the corona I try to work-out a lot for that "September body" (no I'm not fat at all :)). Oooo and I love goats and sheeps.

## Goals
To understand JavaScript and coding in general a lot better. I see myself more as a Designer, but I can HTML and CSS. But want to have a little taste of everything so I can see what might fits me and what not. 

## Skill level
Still a beginner, have learned Javascript in the past but I always found it very hard. I can read the JavaScript code quite well but typing it myself seems always to be a struggle. I hope I will hit the note soon so I can pop off. 

## GitHub username
mikehov

## GitHub repository
https://github.com/mikehov/js-bootcamp

**Comment by dandevri** [comment]
👋 Mike

Looks ok, but I don't see a ton of exercises and notes. You'll probably want to expand on your notes for front-end, you'll need these notes later!
