### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Vuurvos1** [cmda-bt/js-bootcamp-19-20#39]
# My Introduction

## Name
Sam de Kanter

## Class
Tech 4

## About me
uber nerd and Moffel fanatic

## Goals
Learn more about the backend and the web in general

## Skill level
 advanced

## GitHub username
Vuurvos1

## GitHub repository
https://github.com/Vuurvos1/js-bootcamp

**Comment by dandevri** [comment]
👋 Sam

Looks ok! I see quite some code examples. You might want to expand on your notes a bit while you continue working on front-end. You'll need those later!
