### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by SjorsWijsman** [cmda-bt/js-bootcamp-19-20#40]
# My Introduction

## Name

Sjors Wijsman

## Class

Tech 4

## About me

CMD Student met ambitie om frontend developer te worden, denk ik. Woonachtig in Leusden nabij Amersfoort. 1 jaar ICT gestudeerd in Utrecht waar ik Python en Java heb geleerd. Zelfstandig JS/HTML/CSS geleerd. Momenteel C# en JS (verder) aan het leren.

## Skill level

Intermediate. Comfortabel in JavaScript maar er is altijd meer te leren.

## GitHub username

https://github.com/SjorsWijsman/

## GitHub repository

https://github.com/SjorsWijsman/js-bootcamp

**Comment by dandevri** [comment]
👋 Sjors

The exercises look good! Why didn't you take any notes? Those are important as you will also need them for the front-end course.
