### ISSUE TITLE
JS Bootcamp Repository

### ISSUE THREAD

**Issue by NathanNeelis** [cmda-bt/js-bootcamp-19-20#42]
# My Introduction

## Name
Nathan Neelis

## Class
Tech - 4

## About me
Hard-working student 

## Skill level
Beginner @ JS

## GitHub username
[/NathanNeelis](https://github.com/NathanNeelis)    

## GitHub repository
[Bootcamp repository](https://github.com/NathanNeelis/js-bootcamp/tree/master)

**Comment by dandevri** [comment]
👋 Nathan

I see a ton of exercises, good! You might want to expand on your notes a bit while you continue working on front-end. You can also write these notes in markdown format in your wiki.
