### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Bjornborgie** [cmda-bt/js-bootcamp-19-20#43]
# My Introduction

## Name
Björn Kouw
## Class
Tech 4
## About me
Hi  I'm a fourth-year UX Design student with the ambition to start with the master Information Systems
## Skill level
Beginner
## GitHub username
https://github.com/Bjornborgie
## GitHub repository
https://github.com/Bjornborgie/Javascript-bootcamp2020

**Comment by dandevri** [comment]
👋 Bjorn

Looks pretty good! I see a ton of code examples, you might want to expand on your notes a bit while you continue working on front-end. It's also ok to write in `markdown` instead of HTML!
