### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by rosavoogd** [cmda-bt/js-bootcamp-19-20#44]
# My Introduction

## Name
Rosa Voogd

## Class
Tech-4

## Skill level
Beginner

## GitHub username
https://github.com/rosavoogd

## GitHub repository
https://github.com/rosavoogd/bootcamp

**Comment by dandevri** [comment]
👋 Rosa

Your repository seems empty, did you commit your files or add them to your GitHub repository trough the web interface?
