### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by RowinRuizendaal** [cmda-bt/js-bootcamp-19-20#46]
# My Introduction

## Name
Rowin Ruizendaal

## Class
TECH_4

## About me
Hey! My name is Rowin Ruizendaal. I'm a front-end developer. I love technology I'm currently working at MediaLab as a front-end developer.

## Skill level
intermediate

## GitHub username
https://github.com/rowinruizendaal

## GitHub repository
https://github.com/RowinRuizendaal/js-bootcamp-19-20-Rowin

**Comment by dandevri** [comment]
👋 Rowin

Nice job on the exercises! You'll probably want to expand your notes a bit while you continue working on front-end, those are a bit minimal.
