### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by bommezijn** [cmda-bt/js-bootcamp-19-20#48]
# My Introduction

## Name
Nathan B

## Class
TECH-4

## About me
Aspiring Entry-level developer. Interest in design and technology

## Skill level
Beginner

## GitHub username
[Dewarian](www.github.com/dewarian)

## GitHub repository
[JS-Bootcamp by Nathan B](https://github.com/dewarian/js-bootcamp)

**Comment by dandevri** [comment]
👋 Nathan

Looks pretty good! You might want to expand on your notes a bit while you continue to work on front-end.
