### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Falicer** [cmda-bt/js-bootcamp-19-20#52]
# My Introduction

## Name

Raekwon Gerold, just call me Ray

## Class

Tech-4

## About me

Just someone trying his best, enjoying relaxing night moments with music.

## Skill level

Beginner

## GitHub username

[Falicer](https://github.com/Falicer)

## GitHub repository

[Project Tech repository](https://github.com/Falicer/Blok_Tech)

**Comment by dandevri** [comment]
👋 Raekwon

Good start! But I don't see any 'real notes'? It all feels a bit 'scanty', you might want to add more notes while you continue working on front-end.
