### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by SimonPlanje** [cmda-bt/js-bootcamp-19-20#56]
# My Introduction

## Name
Simon Planje

## Class
Tech 4

## About me
Ik ben Simon 19 jaar oud, en heb nog redelijk weinig ervaring met Javascript. Ik heb dit jaar en vorig jaar enorm veel lol gehad met het spelen met html en css, ook heb ik voor mijn stage veel met arduino gewerkt, ik ben dus denk ik redelijk technisch ingesteld en heb zin om meer te gaan leren over Javascript.

## Skill level
Ik zit tussen een beginner en intermediate in. Ik ben voordat we dit blok waren gestart al begonnen aan de javascript course van DevEd, dit heeft mij een goede basis kennis gegeven.

## GitHub username
https://github.com/SimonPlanje

## GitHub repository
https://github.com/SimonPlanje/javascriptbootcamp

**Comment by dandevri** [comment]
👋 Simon

Good start! Your notes feel a bit 'scanty', you might want to add more notes while you continue working on front-end.  I see a couple of exercises so that looks good.
