### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by AsaMarjew** [cmda-bt/js-bootcamp-19-20#58]
# My Introduction

## Name
Asa Marjew

## Class
202

## Skill level
Intermediate

## GitHub username
https://github.com/AsaMarjew

## GitHub repository
https://github.com/AsaMarjew/js-bootcamp-19-20/tree/master/template-repo

**Comment by dandevri** [comment]
👋 Asa

Good start! Your repo does feel a bit 'scanty', you might want to add more notes while you continue working on front-end.
