### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by ParvinBDJ** [cmda-bt/js-bootcamp-19-20#59]
# My Introduction

Hoi, ik ben Parvin. Ik ben nogal onbekend met Javascript dus voor mij is het allemaal nieuw.

## Name
Parvin Bungenberg de Jong

## Class
203

## Skill level
Beginner

## GitHub username
https://github.com/ParvinBDJ

## GitHub repository
https://github.com/ParvinBDJ/js-bootcamp

**Comment by dandevri** [comment]
👋 Parvin

Good start! Your repo does feel a bit 'scanty', you might want to add more notes while you continue working on front-end.
