### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by uxtothemax** [cmda-bt/js-bootcamp-19-20#61]
# My Introduction

Dit is mijn repo voor de JS bootcamp. Tot nu toe heb ik alles in Word documentjes staan, maar dit zal ik waarschijnlijk nog moeten overzetten naar mijn wiki óf anders moeten aanpakken bij de rest van het blok.

## Name
Romy

## Class
Tech-4

## About me
Op dit moment volg ik Fantasy High van Dimension 20.

## Skill level
Beginner

## GitHub username
https://github.com/uxtothemax/

## GitHub repository
https://github.com/uxtothemax/JS-bootcamp

**Comment by dandevri** [comment]
👋 Romy

Your repository seems empty, did you commit your files or add them to your GitHub repository trough the web interface?
