### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by saskiapool** [cmda-bt/js-bootcamp-19-20#63]
# My Introduction

## Name
 Saskia

## Class
tech 4

## About me
Want to learn more about the technical side of CMD

## Skill level
beginner

## GitHub username
https://github.com/saskiapool

## GitHub repository
https://github.com/saskiapool/js-bootcamp

**Comment by dandevri** [comment]
👋 Saskia

Your repository seems empty, did you commit your files or add them to your GitHub repository trough the web interface?

**Comment by saskiapool** [comment]
Ooh, I created a wiki with my files :) https://github.com/saskiapool/js-bootcamp/wiki
