### ISSUE TITLE
Repository Bootcamp

### ISSUE THREAD

**Issue by Sanne1998HvA** [cmda-bt/js-bootcamp-19-20#65]
# My Introduction

## Name
Sanne Kes

## Class
203 

## About me
HEY YOU! Ik ben Sanne Kes, afgestudeerd grafisch vormgever en beginnend frontend ( en hopelijk nu ook meer backend  ) developer. Ik ben gefascineerd over UX en html CSS, maar vind javascript nog een uitdaging.  

## Skill level

ik zou mijzelf als beginner omschrijven. Ben nog erg zoekende maar ik vind het wel reuze interessant. 

## GitHub username
https://github.com/Sanne1998HvA

## GitHub repository
https://github.com/Sanne1998HvA/bootcampJS

**Comment by dandevri** [comment]
👋 Sanne

Your repository seems empty, did you commit your files or add them to your GitHub repository trough the web interface?
